### ISSUE TITLE
Website needs update

### ISSUE THREAD

**Issue by Mcaserza** [commhill/commhill.github.io#12]
We have dumpster day, spring Litter clean-up, etc coming up. Also a lot of construction links are broken. Most links give this error 

The account being accessed does not support http.
HttpStatusCode: 400
ErrorCode: AccountRequiresHttps
RequestId : bf107636-701e-006a-5597-5da9f5000000
TimeStamp : 2023-03-23T14:53:32.8249865Z

**Comment by bringhurst** [comment]
Hey, thank you for reporting this!

It looks like azure started enforcing TLS on buckets, and it broke the CDN connection.

I just enabled TLS between the CDN and Azure, which seems to have resolved it.

I think it may be too late to add the dumpster day info. I don't seems to have a good copy of the flyer either. Maybe next time.
